# Generated by Django 3.2.15 on 2023-04-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcb', '0005_auto_20230407_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='state',
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
