# Generated by Django 3.2.15 on 2023-04-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcb', '0007_auto_20230407_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='fields',
            new_name='field',
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='users'),
        ),
    ]
