# Generated by Django 3.2.15 on 2023-04-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcb', '0008_auto_20230407_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='field',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
