# Generated by Django 3.2.15 on 2023-05-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcb', '0010_auto_20230506_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
