# Generated by Django 3.2.15 on 2023-05-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcb', '0011_user_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_date',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('DONE', 'DONE'), ('CANCEL', 'CANCEL')], default='PENDING', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
