# Generated by Django 3.2.15 on 2023-05-12 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcb', '0015_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='body',
            new_name='content',
        ),
    ]
