# Generated by Django 3.2.15 on 2023-05-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcb', '0018_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='fee',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
