# Generated by Django 3.2.15 on 2023-05-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcb', '0019_auto_20230527_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='price',
        ),
        migrations.AddField(
            model_name='doctor',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
